JS&jQuery 最終課題
shogo-matsumura/-js_lesson pull request #1
Opened 2024-05-09 07:37 UTC by shogo-matsumura

# やったこと
動画の挙動に沿ったJavaスクリプトのコードを作成しました。

2024-05-09 09:15 UTC, cin-sakino requested changes
いくつかコメントさせていただきました！

2024-05-09 09:15 UTC, cin-sakino commented on 2_4/script.js
> +        }
ここは単純に入力された値を表示する感じで良いですよ！

2024-05-09 09:15 UTC, cin-sakino commented on 2_1/index.html
> +
余分な空白行は削除しておきましょう！
他にもいくつかあるので同様にお願いいたします！

2024-05-09 09:15 UTC, cin-sakino commented on 2_1/script.js
> +    console.log('button');
これはデバック用だと思うので消しておきましょう！

2024-05-09 09:40 UTC, shogo-matsumura commented on 2_4/script.js
> +        }
ありがとうございます。
指定外の実装で申し訳ございません。
勉強がてら他の数字を入れた時の挙動をいれただけでした。
2-5でも同様の内容を施したため、そちらも修正済みです。

2024-05-09 09:40 UTC, shogo-matsumura commented on 2_1/script.js
> +    console.log('button');
ありがとうございます。おっしゃる通りです。削除済み

2024-05-09 10:28 UTC, cin-sakino requested changes
色々とご自分で試されていて素晴らしいです！🥳
１つだけコメントさせていただきました！

2024-05-09 10:28 UTC, cin-sakino commented on 2_4/script.js
> +        }
ここは1か２だけを考慮するのではなく、シンプルに入力された値をalertで表示するようにしましょう！

2024-05-09 11:48 UTC, shogo-matsumura commented on 2_4/script.js
> +        }
ありがとうございます。
if, elseを使うのではなく修正を完了しました。
合わせて本項目でvar を使用してしまっていたため、letに変更しております。

2024-05-10 01:31 UTC, cin-sakino approved these changes
💯

2024-06-21 03:14 UTC, merged